const app=document.getElementById('app');let token=localStorage.getItem('am_token');let state=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(p,o={}){const r=await fetch(p,{...o,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(o.headers||{})}});const x=await r.json().catch(()=>({}));if(r.status===401){token=null;localStorage.removeItem('am_token');renderAuth();}if(!r.ok)throw new Error(x.error||'Request failed');return x}
function renderAuth(){app.innerHTML=`<main class="landing"><nav><div class="brand">✦ <b>AuraMend</b><span>AI</span></div><button class="ghost" onclick="showLogin()">Sign in</button></nav><section class="hero"><div class="eyebrow">AI AGENTS FOR MODERN BUSINESSES</div><h1>Your website should <i>talk back.</i></h1><p>Deploy a branded AI agent that answers questions, captures leads and helps book appointments—without coding.</p><div class="actions"><button class="primary" onclick="showRegister()">Start free</button><button class="ghost" onclick="demo()">Try the live agent →</button></div><div class="demo-card"><div class="demo-top"><span>● LIVE</span><b>AuraMend AI</b></div><div class="bubble">Hi! I’m Aura. Ask me about services, pricing or appointments.</div><div class="bubble user">How much is a consultation?</div><div class="bubble">Consultations start at $99. I can also help you book.</div></div></section><section class="features"><article><b>01 · Train</b><h3>Connect your knowledge</h3><p>Give AuraMend approved business information and keep answers grounded.</p></article><article><b>02 · Deploy</b><h3>One-line installation</h3><p>Generate a secure widget key and add the agent to any website.</p></article><article><b>03 · Convert</b><h3>Turn chats into action</h3><p>Capture qualified leads and build appointment workflows around conversations.</p></article></section></main>`}
function showLogin(){app.innerHTML=`<div class="auth"><div class="auth-box"><div class="brand">✦ <b>AuraMend</b><span>AI</span></div><h1>Welcome back</h1><p>Sign in to your customer portal.</p><form onsubmit="login(event)"><input id="email" type="email" placeholder="Email" required><input id="password" type="password" placeholder="Password" required><button class="primary">Sign in</button></form><button class="link" onclick="showRegister()">Create an account →</button><button class="link muted" onclick="renderAuth()">← Back</button></div></div>`}
function showRegister(){app.innerHTML=`<div class="auth"><div class="auth-box"><div class="brand">✦ <b>AuraMend</b><span>AI</span></div><h1>Build your agent</h1><p>Start with a free workspace.</p><form onsubmit="register(event)"><input id="business" placeholder="Business name" required><input id="name" placeholder="Your name"><input id="email" type="email" placeholder="Work email" required><input id="password" type="password" minlength="8" placeholder="Password (8+ characters)" required><input id="website" placeholder="Website URL (optional)"><button class="primary">Create workspace</button></form><button class="link" onclick="showLogin()">Already have an account? Sign in</button></div></div>`}
async function login(e){e.preventDefault();try{const x=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:email.value,password:password.value})});token=x.token;localStorage.setItem('am_token',token);load()}catch(x){alert(x.message)}}
async function register(e){e.preventDefault();try{const x=await api('/api/auth/register',{method:'POST',body:JSON.stringify({businessName:business.value,name:name.value,email:email.value,password:password.value,website:website.value})});token=x.token;localStorage.setItem('am_token',token);load()}catch(x){alert(x.message)}}
async function load(){state=await api('/api/dashboard');renderDash()}
function renderDash(){const a=state.agent;app.innerHTML=`<div class="portal"><aside><div class="brand">✦ <b>AuraMend</b><span>AI</span></div><nav><a class="active">Dashboard</a><a>AI Agent</a><a>Knowledge Base</a><a>Conversations</a><a>Leads</a><a>Appointments</a><a>Analytics</a><a>Billing</a><a>Settings</a></nav><div class="account"><b>${esc(state.org.name)}</b><span>${esc(state.org.role||'Owner')}</span><button onclick="logout()">Sign out</button></div></aside><main class="dash"><header><div><span class="eyebrow">CUSTOMER PORTAL</span><h1>Good afternoon 👋</h1><p>Your AI agent is ready to work.</p></div><button class="primary" onclick="openChat()">Test agent</button></header><section class="stats"><div><span>AI chats</span><strong>${state.conversations.length}</strong></div><div><span>Leads</span><strong>${state.leads.length}</strong></div><div><span>Appointments</span><strong>${state.appointments.length}</strong></div><div><span>Plan</span><strong>${esc(state.subscription?.plan||'starter')}</strong></div></section><section class="grid"><div class="card hero-card"><div><span class="pill">● LIVE</span><h2>${esc(a.name)} is working</h2><p>${esc(a.greeting)}</p><button class="ghost" onclick="openChat()">Open live preview →</button></div><div class="orb">✦</div></div><div class="card"><div class="card-head"><h3>Agent</h3><button class="small" onclick="editAgent()">Edit</button></div><p><b>${esc(a.name)}</b></p><p class="muted">${esc(a.personality)}</p><p class="muted">Proactive messages: ${a.proactive?'On':'Off'}</p></div></section><section class="grid two"><div class="card"><div class="card-head"><h3>Knowledge base</h3><button class="small" onclick="addKnowledge()">+ Add source</button></div>${state.knowledge.map(k=>`<div class="row"><div><b>${esc(k.title)}</b><span>${esc(k.content.slice(0,100))}${k.content.length>100?'…':''}</span></div><button class="icon" onclick="delKnowledge('${k.id}')">×</button></div>`).join('')||'<p class="muted">No sources yet.</p>'}</div><div class="card"><div class="card-head"><h3>Recent leads</h3></div>${state.leads.slice(0,6).map(l=>`<div class="row"><div><b>${esc(l.name||'Unknown')}</b><span>${esc(l.email||'No email')}</span></div><span class="pill">${esc(l.status)}</span></div>`).join('')||'<p class="muted">Leads captured from the widget will appear here.</p>'}</div></section><section class="card install"><div><span class="eyebrow">DEPLOY</span><h2>Install your agent</h2><p>Generate a private widget key. It can be rotated at any time.</p></div><button class="primary" onclick="generateKey()">Generate widget key</button><div id="keyout"></div></section></main></div><div id="modal"></div>`}
function modal(x){document.getElementById('modal').innerHTML=`<div class="overlay" onclick="if(event.target===this)closeModal()"><div class="modal">${x}</div></div>`}function closeModal(){document.getElementById('modal').innerHTML=''}
function openChat(){modal(`<div class="chat"><div class="chat-head"><b>${esc(state.agent.name)}</b><button onclick="closeModal()">×</button></div><div id="msgs" class="msgs"><div class="bubble">${esc(state.agent.greeting)}</div></div><div class="chat-input"><input id="chatq" placeholder="Ask your agent…" onkeydown="if(event.key==='Enter')sendChat()"><button class="primary" onclick="sendChat()">Send</button></div></div>`)}
async function sendChat(){const q=document.getElementById('chatq'),v=q.value.trim();if(!v)return;const m=document.getElementById('msgs');m.innerHTML+=`<div class="bubble user">${esc(v)}</div>`;q.value='';const x=await api('/api/chat',{method:'POST',body:JSON.stringify({agentId:state.agent.id,message:v})});m.innerHTML+=`<div class="bubble">${esc(x.reply)}</div>`;m.scrollTop=m.scrollHeight}
function addKnowledge(){modal(`<h2>Add knowledge</h2><p>Only approved information will be used as agent context.</p><input id="kt" placeholder="Source title"><textarea id="kc" rows="8" placeholder="Business information…"></textarea><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveKnowledge()">Add source</button></div>`)}
async function saveKnowledge(){await api('/api/knowledge',{method:'POST',body:JSON.stringify({title:kt.value,content:kc.value})});closeModal();load()}async function delKnowledge(i){if(confirm('Delete this source?')){await api('/api/knowledge/'+i,{method:'DELETE'});load()}}
function editAgent(){const a=state.agent;modal(`<h2>Configure agent</h2><input id="an" value="${esc(a.name)}" placeholder="Agent name"><input id="ag" value="${esc(a.greeting)}" placeholder="Greeting"><input id="ap" value="${esc(a.personality)}" placeholder="Personality"><label class="check"><input id="apr" type="checkbox" ${a.proactive?'checked':''}> Proactive conversations</label><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveAgent()">Save</button></div>`)}
async function saveAgent(){await api('/api/agent',{method:'PUT',body:JSON.stringify({name:an.value,greeting:ag.value,personality:ap.value,proactive:apr.checked})});closeModal();load()}
async function generateKey(){const x=await api('/api/widget-key',{method:'POST'});document.getElementById('keyout').innerHTML=`<div class="key"><b>Private widget key</b><code>${esc(x.key)}</code><p>Use this server-side/inside your generated widget configuration. Do not publish it in source code repositories.</p><button class="ghost" onclick="navigator.clipboard.writeText('${x.key}');this.textContent='Copied'">Copy key</button></div>`}
function demo(){showLogin()}function logout(){token=null;localStorage.removeItem('am_token');renderAuth()}
if(token)load().catch(()=>renderAuth());else renderAuth();
