import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {db,init,one,all,run} from './db.js';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),PUBLIC=path.join(ROOT,'public'),PORT=Number(process.env.PORT||3000),SECRET=process.env.JWT_SECRET||'change-this-secret-before-production';init();
const now=()=>new Date().toISOString(),id=p=>p+'_'+crypto.randomUUID(),b64=x=>Buffer.from(x).toString('base64url'),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
function jwt(payload){const h=b64(JSON.stringify({alg:'HS256',typ:'JWT'})),p=b64(JSON.stringify({...payload,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+604800}));const s=crypto.createHmac('sha256',SECRET).update(h+'.'+p).digest('base64url');return h+'.'+p+'.'+s}
function verify(t){try{const [h,p,s]=t.split('.');const expected=crypto.createHmac('sha256',SECRET).update(h+'.'+p).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(expected)))throw 0;const x=JSON.parse(Buffer.from(p,'base64url'));if(x.exp<Date.now()/1000)throw 0;return x}catch{return null}}
function pwHash(p,salt=crypto.randomBytes(16).toString('hex')){return `${salt}:${crypto.scryptSync(p,salt,32).toString('hex')}`}function pwOk(p,v){const [s,h]=String(v).split(':');if(!s||!h)return false;return crypto.timingSafeEqual(Buffer.from(h,'hex'),crypto.scryptSync(p,s,32))}
const seed=()=>{if(one('SELECT id FROM users LIMIT 1'))return;const u=id('usr'),o=id('org'),a=id('agt'),t=now();run('INSERT INTO users VALUES(?,?,?,?,?)',[u,'owner@auramend.local',pwHash('ChangeMe123!'),'AuraMend Owner',t]);run('INSERT INTO organizations VALUES(?,?,?,?,?)',[o,'AuraMend Demo Business','https://example.com','Service Business',t]);run('INSERT INTO memberships VALUES(?,?,?)',[u,o,'owner']);run('INSERT INTO agents VALUES(?,?,?,?,?,?,?,?)',[a,o,'Aura','Hi! I’m Aura, your AI assistant. How can I help today?','Friendly, concise, professional','#7c5cff',1,t]);run('INSERT INTO knowledge VALUES(?,?,?,?,?,?)',[id('kn'),o,'Business information','We provide professional consultations and appointments. Monday through Friday, 9 AM to 6 PM. Consultations start at $99. We offer consultations, follow-up sessions, and personalized service plans.',null,t]);run('INSERT INTO subscriptions VALUES(?,?,?,?,?)',[id('sub'),o,'trialing','starter',t]);console.log('Demo login: owner@auramend.local / ChangeMe123!')};seed();
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':process.env.APP_URL||'*','Access-Control-Allow-Headers':'Content-Type, Authorization, X-AuraMend-Key','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'};const send=(res,s,x)=>{res.writeHead(s,headers);res.end(JSON.stringify(x))};const raw=async req=>new Promise((resolve,reject)=>{let x='';req.on('data',c=>{x+=c;if(x.length>2e6)req.destroy()});req.on('end',()=>resolve(x))});const parse=async req=>{const x=await raw(req);try{return x?JSON.parse(x):{}}catch{throw new Error('Invalid JSON')}};
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const p=verify(h.slice(7));return p?.sub?one('SELECT id,email,name FROM users WHERE id=?',[p.sub]):null}function orgFor(u){return one('SELECT o.*,m.role FROM organizations o JOIN memberships m ON m.org_id=o.id WHERE m.user_id=? LIMIT 1',[u.id])}function agent(a){return a&&{id:a.id,name:a.name,greeting:a.greeting,personality:a.personality,color:a.color,proactive:!!a.proactive}}
async function reply(a,orgId,msgs){const ks=all('SELECT title,content FROM knowledge WHERE org_id=? ORDER BY created_at DESC',[orgId]).map(x=>`${x.title}: ${x.content}`).join('\n\n');const last=msgs.at(-1)?.content||'';if(process.env.OPENAI_API_KEY){try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-mini',input:[{role:'system',content:`You are ${a.name}, the business website AI. ${a.personality}. Use only approved knowledge. Never invent facts. If unknown, say so and offer lead capture.\n${ks}`},...msgs.slice(-12).map(m=>({role:m.role==='assistant'?'assistant':'user',content:m.content}))]})});if(r.ok){const j=await r.json();if(j.output_text)return j.output_text}}catch(e){console.error(e.message)}}const q=last.toLowerCase();if(/price|cost|how much/.test(q))return 'Consultations start at $99. I can also collect your details to help you book.';if(/hour|open|close|available/.test(q))return 'We’re available Monday through Friday from 9 AM to 6 PM.';if(/book|appointment|schedule/.test(q))return 'Absolutely. Please share your name, email, preferred date, and service.';return 'I can answer questions about services, pricing, hours, or help collect details for an appointment.'}
let lastRate={};function rate(ip){const n=Date.now(),x=lastRate[ip]||{t:n,c:0};if(n-x.t>60000){x.t=n;x.c=0}x.c++;lastRate[ip]=x;return x.c<=120}
async function route(req,res){if(req.method==='OPTIONS'){res.writeHead(204,headers);return res.end()}if(!rate(req.socket.remoteAddress||'x'))return send(res,429,{error:'Too many requests'});const u=new URL(req.url,'http://localhost'),p=u.pathname;
try{
if(p==='/api/stripe/webhook'&&req.method==='POST'){const body=await raw(req),sig=req.headers['stripe-signature']||'',secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret)return send(res,503,{error:'Stripe webhook not configured'});const m=String(sig).match(/t=(\d+),v1=([^,]+)/);if(!m)return send(res,400,{error:'Invalid signature'});const expected=crypto.createHmac('sha256',secret).update(m[1]+'.'+body).digest('hex');if(!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(m[2])))return send(res,400,{error:'Invalid signature'});const e=JSON.parse(body);const o=e.data?.object;const oid=o?.metadata?.org_id;if(oid){const status=e.type.includes('deleted')?'canceled':(o.status||'active');run('UPDATE subscriptions SET status=?,provider_customer_id=?,provider_subscription_id=? WHERE org_id=?',[status,o.customer||null,o.id||null,oid])}return send(res,200,{received:true})}
if(p==='/api/health')return send(res,200,{ok:true,version:'2.0.0',db:'sqlite',ai:!!process.env.OPENAI_API_KEY});
if(p==='/api/auth/register'&&req.method==='POST'){const b=await parse(req);if(!b.email||!b.password||b.password.length<8||!b.businessName)return send(res,400,{error:'Business name, email and an 8+ character password are required'});if(one('SELECT id FROM users WHERE email=?',[b.email.toLowerCase()]))return send(res,409,{error:'Email already registered'});const u=id('usr'),o=id('org'),a=id('agt'),t=now();run('INSERT INTO users VALUES(?,?,?,?,?)',[u,b.email.toLowerCase(),pwHash(b.password),b.name||b.email.split('@')[0],t]);run('INSERT INTO organizations VALUES(?,?,?,?,?)',[o,b.businessName,b.website||'','Business',t]);run('INSERT INTO memberships VALUES(?,?,?)',[u,o,'owner']);run('INSERT INTO agents VALUES(?,?,?,?,?,?,?,?)',[a,o,'Aura','Hi! How can I help you today?','Friendly, concise, professional','#7c5cff',0,t]);run('INSERT INTO subscriptions VALUES(?,?,?,?,?)',[id('sub'),o,'trialing','starter',t]);return send(res,201,{token:jwt({sub:u}),user:{id:u,email:b.email.toLowerCase(),name:b.name||''}})}
if(p==='/api/auth/login'&&req.method==='POST'){const b=await parse(req),u=one('SELECT * FROM users WHERE email=?',[String(b.email||'').toLowerCase()]);if(!u||!pwOk(b.password||'',u.password_hash))return send(res,401,{error:'Invalid email or password'});return send(res,200,{token:jwt({sub:u.id}),user:{id:u.id,email:u.email,name:u.name}})}
const user=auth(req);
if(p==='/api/me'&&user){return send(res,200,{user,organization:orgFor(user)})}
if(p==='/api/dashboard'&&user){const o=orgFor(user),a=one('SELECT * FROM agents WHERE org_id=? LIMIT 1',[o.id]);return send(res,200,{org:o,agent:agent(a),knowledge:all('SELECT * FROM knowledge WHERE org_id=? ORDER BY created_at DESC',[o.id]),leads:all('SELECT * FROM leads WHERE org_id=? ORDER BY created_at DESC LIMIT 100',[o.id]),appointments:all('SELECT * FROM appointments WHERE org_id=? ORDER BY created_at DESC LIMIT 100',[o.id]),conversations:all('SELECT * FROM conversations WHERE org_id=? ORDER BY updated_at DESC LIMIT 50',[o.id]),subscription:one('SELECT * FROM subscriptions WHERE org_id=?',[o.id])})}
if(p==='/api/agent'&&req.method==='PUT'&&user){const o=orgFor(user),a=one('SELECT * FROM agents WHERE org_id=? LIMIT 1',[o.id]),b=await parse(req);run('UPDATE agents SET name=?,greeting=?,personality=?,color=?,proactive=? WHERE id=?',[b.name||a.name,b.greeting||a.greeting,b.personality||a.personality,b.color||a.color,b.proactive?1:0,a.id]);return send(res,200,agent(one('SELECT * FROM agents WHERE id=?',[a.id])))}
if(p==='/api/knowledge'&&req.method==='POST'&&user){const o=orgFor(user),b=await parse(req);if(!b.title||!b.content)return send(res,400,{error:'Title and content are required'});const k=[id('kn'),o.id,b.title,b.content,b.sourceUrl||null,now()];run('INSERT INTO knowledge VALUES(?,?,?,?,?,?)',k);return send(res,201,{id:k[0],org_id:k[1],title:k[2],content:k[3],source_url:k[4],created_at:k[5]})}
if(p.startsWith('/api/knowledge/')&&req.method==='DELETE'&&user){const o=orgFor(user);run('DELETE FROM knowledge WHERE id=? AND org_id=?',[p.split('/').pop(),o.id]);return send(res,200,{ok:true})}
if(p==='/api/widget-key'&&req.method==='POST'&&user){const o=orgFor(user),a=one('SELECT id FROM agents WHERE org_id=? LIMIT 1',[o.id]),raw=crypto.randomBytes(32).toString('hex');run('INSERT INTO api_keys VALUES(?,?,?,?,?)',[id('key'),a.id,hash(raw),now(),null]);return send(res,201,{key:'am_'+raw,agentId:a.id})}
if(p==='/api/widget/config'){const raw=String(req.headers['x-auramend-key']||'').replace(/^am_/,'');const k=one('SELECT agent_id FROM api_keys WHERE key_hash=?',[hash(raw)]);if(!k)return send(res,401,{error:'Invalid widget key'});run('UPDATE api_keys SET last_used_at=? WHERE key_hash=?',[now(),hash(raw)]);return send(res,200,{agent:agent(one('SELECT * FROM agents WHERE id=?',[k.agent_id]))})}
if(p==='/api/appointments'&&req.method==='POST'){const b=await parse(req),a=one('SELECT org_id FROM agents WHERE id=?',[b.agentId]);if(!a)return send(res,404,{error:'Agent not found'});const x=[id('apt'),a.org_id,b.conversationId||null,b.name||'',b.email||'',b.service||'',b.preferredDate||'',b.preferredTime||'','requested',now()];run('INSERT INTO appointments VALUES(?,?,?,?,?,?,?,?,?,?)',x);return send(res,201,{id:x[0],status:'requested'})}
if(p==='/api/crawl'&&req.method==='POST'&&user){const o=orgFor(user),b=await parse(req),url=String(b.url||'');if(!/^https?:\/\//i.test(url))return send(res,400,{error:'Valid http(s) URL required'});try{const r=await fetch(url,{headers:{'user-agent':'AuraMendBot/1.0'},redirect:'follow'});if(!r.ok)return send(res,400,{error:'Could not fetch website'});let text=(await r.text()).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim().slice(0,100000);const k=[id('kn'),o.id,new URL(url).hostname,text,url,now()];run('INSERT INTO knowledge VALUES(?,?,?,?,?,?)',k);return send(res,201,{id:k[0],title:k[2],content:k[3],source_url:k[4]})}catch{return send(res,400,{error:'Website could not be imported'})}}
if(p==='/api/billing/checkout'&&req.method==='POST'&&user){if(!process.env.STRIPE_SECRET_KEY)return send(res,503,{error:'Stripe billing is not configured'});const o=orgFor(user),b=await parse(req),price=b.plan==='growth'?process.env.STRIPE_PRICE_GROWTH:process.env.STRIPE_PRICE_STARTER;if(!price)return send(res,503,{error:'Stripe price is not configured'});const form=new URLSearchParams({mode:'subscription',success_url:(process.env.APP_URL||'http://localhost:3000')+'/?billing=success',cancel_url:(process.env.APP_URL||'http://localhost:3000')+'/?billing=cancel',customer_email:user.email,'line_items[0][price]':price,'line_items[0][quantity]':'1','subscription_data[metadata][org_id]':o.id});const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{authorization:'Bearer '+process.env.STRIPE_SECRET_KEY,'content-type':'application/x-www-form-urlencoded'},body:form});const x=await r.json();if(!r.ok)return send(res,502,{error:x.error?.message||'Stripe error'});return send(res,200,{url:x.url})}
if(p==='/api/leads'&&req.method==='POST'){const b=await parse(req),a=one('SELECT org_id FROM agents WHERE id=?',[b.agentId]);if(!a)return send(res,404,{error:'Agent not found'});const l=[id('lead'),a.org_id,b.conversationId||null,b.name||'',b.email||'',b.phone||'',b.service||'','new',now()];run('INSERT INTO leads VALUES(?,?,?,?,?,?,?,?,?)',l);return send(res,201,{id:l[0]})}
if(p==='/api/chat'&&req.method==='POST'){const b=await parse(req),a=one('SELECT * FROM agents WHERE id=?',[b.agentId]);if(!a||!b.message)return send(res,400,{error:'Invalid agent or message'});const bearer=auth(req);if(!bearer){const raw=String(req.headers['x-auramend-key']||'').replace(/^am_/,'');const k=one('SELECT agent_id FROM api_keys WHERE key_hash=?',[hash(raw)]);if(!k||k.agent_id!==a.id)return send(res,401,{error:'Widget authentication required'})}let c=b.conversationId?one('SELECT * FROM conversations WHERE id=? AND org_id=?',[b.conversationId,a.org_id]):null;if(!c){c={id:id('conv'),org_id:a.org_id,agent_id:a.id,visitor_id:b.visitorId||null,created_at:now(),updated_at:now()};run('INSERT INTO conversations VALUES(?,?,?,?,?,?)',Object.values(c))}run('INSERT INTO messages VALUES(?,?,?,?,?)',[id('msg'),c.id,'user',String(b.message).slice(0,4000),now()]);const ms=all('SELECT role,content FROM messages WHERE conversation_id=? ORDER BY created_at DESC LIMIT 12',[c.id]).reverse(),r=await reply(a,a.org_id,ms);run('INSERT INTO messages VALUES(?,?,?,?,?)',[id('msg'),c.id,'assistant',r,now()]);run('UPDATE conversations SET updated_at=? WHERE id=?',[now(),c.id]);return send(res,200,{conversationId:c.id,reply:r,agent:agent(a)})}
if(p.startsWith('/api/'))return send(res,404,{error:'Not found'});
let f=p==='/'?'index.html':p.slice(1);if(!f.startsWith('public/')&&!f.includes('..')){const fp=path.join(PUBLIC,f);if(fs.existsSync(fp)&&fs.statSync(fp).isFile()){const ext=path.extname(fp);const types={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'};res.writeHead(200,{'Content-Type':types[ext]||'text/plain'});return res.end(fs.readFileSync(fp))}}res.writeHead(404);res.end('Not found');
}catch(e){console.error(e);return send(res,500,{error:'Internal server error'})}}
http.createServer(route).listen(PORT,()=>console.log(`AuraMend running at http://localhost:${PORT}`));
